### ISSUE TITLE
.so instead of .a

### ISSUE THREAD

**Issue by RobertBerger** [FedericoVaga/libuinput#1]
Hi,

I played around with your library on an embedded device and there are no statically linked libs available.

So I patched a bit your makefiles to generate the library as an .so 

demo Makefile:

```
-LDFLAGS = -static -L$(LIB)/ -luinput
+LDFLAGS = -L$(LIB)/ -luinput
```

library Makefile:

```
-LIB = libuinput.a
+LIB = libuinput.so
...
-CFLAGS = -Wall -ggdb -O2 -I.
-LDFLAGS = -L. -luinput
+CFLAGS = -fPIC -Wall -ggdb -O2 -I.
+LDFLAGS = -L. -luinput -shared
```

**Comment by FedericoVaga** [comment]
Hi Robert,
I'm glad that you are playing with this tiny thing :)

I'll play with it in the next days and include it in the repo. If you can prepare a formal patch it's better.

**Comment by RobertBerger** [comment]
I just sent you a pull request, which is even simpler than what I did above.

```
diff --git a/demo/Makefile b/demo/Makefile
index 811d76d..5bfc7dd 100644
--- a/demo/Makefile
+++ b/demo/Makefile
@@ -1,7 +1,7 @@
 LIB = ..

 CFLAGS = -Wall -ggdb -O2 -I$(LIB)/
-LDFLAGS = -static -L$(LIB)/ -luinput
+LDFLAGS = -L$(LIB)/ -luinput

 DEMOS := keyboard_demo

@@ -15,4 +15,4 @@ demo: $(DEMOS)
 clean:
        rm -f $(DEMOS) *.o *~
```

**Comment by FedericoVaga** [comment]
The makefile now compiles both static and shared library (3 years later ^_^')
